spring.application.name=api-dbc
server.port=8080
# FIPE API
fipe.api.base-url=https://fipe.parallelum.com.br/api/v2
# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

